# .github/workflows/translate.yml
name: Translate Readme

on:
    push:
        branches: ['**']

jobs:
    translate:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                fetch-depth: 3

            - name: Auto Translate
              uses: Lin-jun-xiang/action-translate-readme@v2 # Based on the tag
              with:
                token: ${{ secrets.Action_Bot }} # Based on step2 name
                g4f_provider: g4f.Provider.OpenaiChat # You can change this provider
                langs: "zh-CN" # You can define any langs
